config/routes.rb
Rails.application.routes.draw do

  get 'tags/new'
  get 'search', to: 'search#new', as: 'search'
  get 'login', to: redirect('/auth/google_oauth2'), as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'
  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')
  get 'user/:id', to: 'user#show', as: 'user'
  root to: "sessions#new"

  resources :questions do
    member do
        put "like" => "questions#upvote"
        put "unlike" => "questions#downvote"
				put "close" => "questions#close"
      end
		  resources :answers do
        member do
          put "like" => "answers#upvote"
          put "unlike" => "answers#downvote"
  				put "accept" => "answers#accept"
        end
      end
  end
  resources :user_teams
  resources :teams

end

app/models/question.rb
# frozen_string_literal: true

# contains question related functions
class Question < ApplicationRecord
  validates :subject, presence: true
  validates :description, presence: true

  has_many :answers, dependent: :destroy
  belongs_to :user
  has_many :question_tags, dependent: :destroy
  has_many :tags, through: :question_tags
  has_many :question_accesses
  has_many :question_votes

  UP_DOWN_SCORE = [
    SiteSetting.getvalue('question_up_score'),
    SiteSetting.getvalue('question_down_score')
  ].freeze

  # Following function returns displayable Questions
  def self.get_displayable(user, question_id = nil)
    user_teams_list = user.team_ids
    ques = question_id.present? ? Question.where(id: question_id) : Question.all
    ques.select do |question|
      @team_ids = question.question_accesses.pluck(:team_id)
      (!(@team_ids & user_teams_list).empty? &&
        question[:status_code_id].to_i != 4)
    end
  end

  def can_be_displayed?(user)
    !(question_accesses.pluck(:team_id) & user.team_ids).empty? &&
      status_code_id.to_i != 4
  end

  def can_be_answered?(user)
    @team_ids = question_accesses.select do |access|
      access[:answer_access] == true
    end.pluck(:team_id)
    !(@team_ids & user.team_ids).empty? &&
      status_code_id.to_i != 4
  end

  def can_be_voted?(user)
    @team_ids = question_accesses.select do |access|
      access[:vote_access] == true
    end.pluck(:team_id)
    !(@team_ids & user.team_ids).empty? &&
      status_code_id.to_i != 4
  end

  def self.search(key)
    Question.where('subject LIKE ?', "%#{key}%")
  end

  def user_not_voted?(user)
    question_votes.where(user_id: user.id).empty?
  end

  def user_upvoted?(user)
    question_votes.where('user_id=? AND up_down_vote>0', "#{user.id}").any?
  end

  def user_downvoted?(user)
    question_votes.where("user_id=? AND up_down_vote<=0", "#{user.id}").any?
  end

  def upvote(user)
    if user_not_voted?(user)
      question_votes.create!(user_id: user.id,
                             up_down_vote: UP_DOWN_SCORE[0])
      increment!(:up_vote_count, 1)
    elsif user_downvoted?(user)
      decrement!(:down_vote_count)
      increment!(:up_vote_count)
      question_votes.first.update(up_down_vote: UP_DOWN_SCORE[0])
    end
  end

  def downvote(user)
    if user_not_voted?(user)
      question_votes.create!(user_id: user.id,
                             up_down_vote: UP_DOWN_SCORE[1])
      increment!(:down_vote_count, 1)
    elsif user_upvoted?(user)
      decrement!(:up_vote_count)
      increment!(:down_vote_count)
      question_votes.first.update(up_down_vote: UP_DOWN_SCORE[1])
    end
  end

  def tags
    @tags = ''
    question_tags.each do |question_tag|
      @tags += '"' + question_tag.tag.name + '",'
    end
    @tags = @tags[0...-1]
  end

  def destroy_tags
    QuestionTag.where(question_id: id).destroy_all
  end

  def destroy_question_accesses
    QuestionAccess.where(question_id: id).destroy_all
  end

  def close
    update(status_code_id: 3)
  end

  def destroy
    update(status_code_id: 4)
  end

  def process_question_accesses(params)
    if params.key?(:view_access)
      params[:view_access].each do |i|
        question_accesses.create!(team_id: i)
      end
    else
      flash[:danger] = 'View Level is minimum'
      return false
    end

    if params.key?(:answer_access)
      params[:answer_access].each do |i|
        QuestionAccess.where(question_id: id,
                             team_id: i).update_all(answer_access: true)
      end
    end

    return unless params.key?(:vote_access)

    params[:vote_access].each do |i|
      QuestionAccess.where(question_id: id,
                           team_id: i). update_all(vote_access: true)
    end
    true
  end

  def process_tags(params)
    tags = params['hidden-tags'].split(',')
    return false if tags.empty?

    tag = nil
    tags.each do |i|
      tag = Tag.find_by(name: i)
      tag ||= Tag.create(name: i)
      question_tags.create!(tag_id: tag.id)
    end
    true
  end
end

app/controllers/questions_controller.rb
# frozen_string_literal: true

# This class contains methods related to Questions
class QuestionsController < ApplicationController
  before_action :authenticate
  before_action :check_user_has_teams
  before_action :set_question, only: %i[show edit update destroy upvote
                                        downvote check_same_user close]
  before_action :check_same_user, only: %i[edit update destroy close]

  def index
    @questions = Question.get_displayable(current_user).paginate(
      page: params[:page],
      per_page: 10
    )
  end

  def show
    unless @question.can_be_displayed?(current_user)
      flash[:danger] = 'You are not allowed to view this question'
      redirect_to root_path
    end
    @answers = Answer.get_displayable(@question.id).paginate(
      page: params[:page],
      per_page: 10
    )
  end

  def new
    @question = Question.new
    @tags = ''
    @teams = current_user.user_teams
  end

  def edit
    @tags = @question.tags
  end

  def create
    @question = current_user.questions.new(params_require)
    if @question.save
      if @question.process_tags(params)
        if @question.process_question_accesses(params)
          flash[:success] = 'Question added successfully'
          redirect_to root_path
        end
      else
        flash[:danger] = 'Minimum one tag is required'
      end
    else
      render 'new'
    end
  end

  def update
    @question.update(params_require)
    @question.destroy_tags
    @question.destroy_question_accesses
    if @question.process_tags(params)
      if @question.process_question_accesses(params)
        flash[:success] = 'Question updated successfully'
      end
    else
      flash[:danger] = 'Minimum one tag is required'
    end
    redirect_to question_path(@question)
  end

  def downvote
    flash[:success] = 'Downvote success' if @question.downvote(current_user)
    redirect_to question_path(@question)
  end

  def upvote
    flash[:success] = 'Upvote success' if @question.upvote(current_user)
    redirect_to question_path(@question)
  end

  def close
    flash[:success] = 'Question Closed successfully' if @question.close
    redirect_to questions_path
  end

  def destroy
    flash[:success] = 'Question deleted successfully' if @question.destroy
    redirect_to questions_path
  end

  def set_question
    @question = Question.find(params[:id])
  end

  private

  def params_require
    if params[:all].to_i == 1
      params[:view_access] = current_user.team_ids
      params[:answer_access] = current_user.team_ids
      params[:vote_access] = current_user.team_ids
    end
    params.require(:question).permit(:subject,
                                     :description,
                                     :team_id)
  end

  def check_same_user
    return if same_user?(@question.user_id)

    flash[:danger] = 'You dont have privileges to perform this action'
    redirect_to questions_path
  end
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/questions/_form.html.erb
<br>
<%= render 'shared/errors', obj: @question %>
<div class="container">
	<div class="row">
		<div class="col-md-12">
			<div class="card">
				<div class="card-header"><%= type %> Question</div>
            <%= form_for(obj) do |f| %>
                <li class="list-group-item">
                <div class="form-group">
                	<br><br>
                    <%= f.label :Subject %><br>
                    <%= f.text_field :subject,class:'form-control' %><br>
                </div>
            </li>


            <li class="list-group-item">
                <div class="form-group">
                   <%= f.label :AskQuestion %><br>
                   <%= f.text_area :description,class:'form-control',rows:10 %><br>
                 </div>
             </li>


             <li class="list-group-item">
                <div class="form-group">
                   <%= f.label :tags %><br>
             <input type="text" name="tags" placeholder="Tags" class="tm-input"/><br>
                 </div>
             </li>

            <li class="list-group-item">
                <div class="form-group">
                    <br><br>
                    <%= f.label :Under_Which_Category_you_want_to_post_this_question %><br>
             <%= f.select(:team_id, options_for_select(current_user.user_teams.collect{|p| [p.team.team_name,p.team.id]}, obj.team_id),{include_blank: true},{:class => 'form-control', :required => true}) %><br>
                </div>
            </li>


             <li class="list-group-item">
                <div class="form-group">
									<table>
										<tr>
											<td>All </td>
											<td> &nbsp</td>
											<td>
												<%= check_box_tag('All', value = 1, checked = (@access)) %>
												</td>
											</tr>
										</table>
             <table class="table table-bordered">
     <thead>
      <tr>
        <th>Team Name</th>
        <th>View Access</th>
        <th>Answer Access</th>
        <th>Vote Access</th>
      </tr>
     </thead>
     <tbody>
        <!--
            checked = ((obj.question_accesses.where(team_id: tea.id).first[:answer_access]) if obj.question_accesses.where(team_id: tea.id).any?)

        -->
        <% current_user.user_teams.each do |tea|
            @access=obj.question_accesses.where(team_id: tea.team_id).any?
            %>
      <tr>
        <td><%= tea.team.team_name %></td>
        <td><%= check_box_tag('view_access[]', value = tea.team_id, checked = (@access)) %></td>
        <td><%= check_box_tag('answer_access[]',value = tea.team_id, checked = (obj.question_accesses.where(team_id: tea.team_id).first[:answer_access] if @access)) %></td>
        <td><%= check_box_tag('vote_access[]', value = tea.team_id, checked = (obj.question_accesses.where(team_id: tea.team_id).first[:vote_access] if @access)) %></td>
      </tr>
      <% end %>
    </tbody>
    </table>
    </div>
    </li>

             <li class="list-group-item">
                 <div class="form-group">
                <%= f.submit("#{type} Question", class:'btn btn-primary input-medium') %>
            </div>
             </li>



             <script type="text/javascript">
                 $(".tm-input").tagsManager({prefilled: [<%= "#{tags}".html_safe %>]});
             </script>


                </div>
            <% end %>
        </div>
	</div>
</div>

app/views/questions/_questiondisplay.html.erb
  <table width="100%" cellpadding="15">
    <% obj.each do |question| %>

                <tr style='border-bottom:1px solid black; '>
                  <td width="10%">
              <% if question.can_be_voted?(current_user) %>
              <span class="row">
              <span class="text-center">
                <%= link_to like_question_path(question),class:"like",method: :put do %>
               <i class="fa fa-thumbs-up fa-2x" aria-hidden="true"></i>
               <% end %>
                <h3><%= question.up_vote_count %></h3>
              </span>

               <span class="text-center" style="padding-left: 13px;">
                 <%= link_to unlike_question_path(question),class:"like",method: :put do %>
               <i class="fa fa-thumbs-down fa-2x" aria-hidden="true"></i>
               <% end %>
                <h3><%= question.down_vote_count %></h3>
              </span>
            </span>
            <% end %>
            </td>
            <td>
            <span>
             <%= link_to question.subject, question_path(question), class:'text-gray-dark' %>
             <br>
             <span>
              <%
              question.question_tags.each do |question_tag|
              %>
              <span class="badge badge-dark"><%= question_tag.tag.name %></span>
              <% end %>
            </span>
              </span>
                </td>
                <td>
              <span>
              <% if question.status_code_id ==3 %>
              <span class="badge badge-warning">Question Closed</span>
              <% elsif question.status_code_id ==2 %>
              <span class="badge badge-success">Answer Accepted</span>
              <% end %>

              <% if(current_user == question.user) && question.status_code_id !=3 %>
              <%= link_to 'Edit', edit_question_path(question), class: 'btn btn-info' %>
              <%= link_to 'Delete', question_path(question),method: :delete, data:{confirm:'Are you sure?'}, class: 'btn btn-danger' %>
              <%= link_to 'Close', close_question_path(question),method: :put, data:{confirm:'Are you sure?'}, class: 'btn btn-danger' %>
              <% end %>
            </span>
            </td>
            </tr>
        <% end %>
</table>

app/views/questions/edit.html.erb
<%= render 'form', obj: @question, tags: @tags, type: "Update" %>

app/views/questions/index.html.erb
<div class="container">
<br>
<div class="text-right">
  <%= link_to "Ask Question",new_question_path,class: "btn btn-primary btn-lg" %>
</div>
 <div class="my-3 p-3 bg-white rounded box-shadow">
   <div class="col-md-12">
        <h6 class="border-bottom border-gray pb-2 mb-0">Questions</h6>
        <%= render 'questions/questiondisplay', obj: @questions %>
        <%= will_paginate @questions %>
      </div>
      </div>
</div>

app/views/questions/new.html.erb
<%= render 'form', obj: @question, tags: @tags, type: "Create" %>

app/views/questions/show.html.erb
<br>
<div class="container">
  <div class="card">
    <div class="card-header"><%= @question.subject %></div>
    <ul class="list-group list-group-flush">

    <li class="list-group-item"><%= @question.description %>

    <li class="list-group-item">
      <table class="pull-center">
        <tr>

        <% if @question.can_be_voted?(current_user) %>
        <td>
      <span class="text-center">
        <%= link_to like_question_path(@question),class:"like",method: :put do %>
       <i class="fa fa-thumbs-up fa-2x" aria-hidden="true"></i>
       <% end %>
        <h3><%= @question.up_vote_count %></h3>
      </span>
      </td>
      <td>
       <span class="text-center" style="padding-left: 13px;">
         <%= link_to unlike_question_path(@question),class:"like",method: :put do %>
       <i class="fa fa-thumbs-down fa-2x" aria-hidden="true"></i>
       <% end %>
        <h3><%= @question.down_vote_count %></h3>
      </span>
      </td>
      <% end %>
      <% if @question.can_be_answered?(current_user) && @question.status_code_id != 3 %>
        <td>
    	<%= link_to  "Click here to answer",new_question_answer_path(@question), class: 'btn btn-primary pull-right' %>
      </td>
      <% end %>
      </tr></table>
      </li>


  </ul>
  </div>
  <br>
  <div class="card">
  	<div class="card-header">
  <%= @answers.count %> Answers</div>
    <ul class="list-group list-group-flush">

      <%= will_paginate @answers %>

    	<% @answers.each do |answer| %>
    <li class="list-group-item">

      <span style="border: 1px solid black;padding: 10px;background: darkkhaki;">
        <%= image_tag answer.user.picture,class: 'rounded-circle',height: '40px' %>
        <%= answer.user.first_name %></span><br><br>

      <%= answer.description %>
      <% if current_user == answer.user %>
      <div class="text-right" style="float:right;">

        <table>
          <tr>
            <td>
              <% if answer.status == true %>
              <span class="badge badge-success">Answer Accepted</span>
              <% end %>
              </td>
            <% if @question.can_be_voted?(current_user) %>
            <td>
         <span class="text-center">
               <%= link_to like_question_answer_path(@question.id,answer),class:"like",method: :put do %>
               <i class="fa fa-thumbs-up fa-2x" aria-hidden="true"></i>
               <% end %>

                <h3><%= answer.up_vote_count %></h3>
              </span>
              </td>
              <td>
              <span class="text-center" style="padding-left: 13px;">
                 <%= link_to unlike_question_answer_path(@question.id,answer),class:"like",method: :put do %>
               <i class="fa fa-thumbs-down fa-2x" aria-hidden="true"></i>
               <% end %>
                <h3><%= answer.down_vote_count %></h3>
              </span>
              </td>
              <% end %>
              <td>
      <%= link_to  "Edit",edit_question_answer_path(@question,answer), class: 'btn btn-info text-right' %>
              </td>
              <td>
      <%= link_to  "Delete",question_answer_path(@question,answer),method: :delete, data:{confirm:'Are you sure to delete Answer?'}, class: 'btn btn-danger text-right' %>
            </td>
      <% if @question.user_id == current_user.id && @question.status_code_id != 2 %>
      <td>
      <%= link_to  "Mark as Answer",accept_question_answer_path(@question.id,answer),method: :put, data:{confirm:'Are you sure to Mark this answer?'}, class: 'btn btn-success text-right' %>
        </td>
        <% end %>
      </tr></table>

    </div>
    <% end %>
    </li>
    	<% end %>
  </ul>
  </div>
</div>