config/routes.rb
Rails.application.routes.draw do

  get 'tags/new'
  get 'search', to: 'search#new', as: 'search'
  get 'login', to: redirect('/auth/google_oauth2'), as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'
  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')
  get 'user/:id', to: 'user#show', as: 'user'
  root to: "sessions#new"

  resources :questions do
    member do
        put "like" => "questions#upvote"
        put "unlike" => "questions#downvote"
				put "close" => "questions#close"
      end
		  resources :answers do
        member do
          put "like" => "answers#upvote"
          put "unlike" => "answers#downvote"
  				put "accept" => "answers#accept"
        end
      end
  end
  resources :user_teams
  resources :teams

end

app/controllers/search_controller.rb
# frozen_string_literal: true

# This class contains methods related to search
class SearchController < ApplicationController
  def new
    @key = params[:search][:key]
    if @key.length >= 1
      @results = Question.search(@key).paginate(page: params[:page],
                                                per_page: 10)
    else
      flash[:danger] = 'search term cannot be empty'
      redirect_to questions_path
    end
  end
end

app/views/search/new.html.erb
<br>
<div class="container"%>
<%= will_paginate @results%>
<table class="table">
    <thead>
      <tr>
        <th>Question</th>
        <th>Upvotes</th>
        <th>Downvotes</th>
      </tr>
    </thead>
    <tbody>
      <% @results.each do |result| %>
      <tr>
        <td><%= link_to result.subject,question_path(result),target: 'blank' %></td>
        <td><%= result.up_vote_count %></td>
        <td><%= result.down_vote_count %></td>
      </tr>
      <% end %>
      </tbody>
      </table>
</div>