config/routes.rb
Rails.application.routes.draw do

  get 'tags/new'
  get 'search', to: 'search#new', as: 'search'
  get 'login', to: redirect('/auth/google_oauth2'), as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'
  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')
  get 'user/:id', to: 'user#show', as: 'user'
  root to: "sessions#new"

  resources :questions do
    member do
        put "like" => "questions#upvote"
        put "unlike" => "questions#downvote"
				put "close" => "questions#close"
      end
		  resources :answers do
        member do
          put "like" => "answers#upvote"
          put "unlike" => "answers#downvote"
  				put "accept" => "answers#accept"
        end
      end
  end
  resources :user_teams
  resources :teams

end

app/models/user.rb
# frozen_string_literal: true

# This class contains User related functions
class User < ApplicationRecord
  has_many :questions
  has_many :answers
  has_many :user_teams, dependent: :destroy
  has_many :team_admins
  has_many :teams, through: :team_admins
  has_many :teams, through: :user_teams

  def self.find_or_create_from_auth_hash(auth)
    where(provider: auth.provider, uid: auth.uid)
      .first_or_initialize.tap do |user|
      user.attributes = {
        provider: auth.provider,
        uid: auth.uid,
        first_name: auth.info.first_name,
        last_name: auth.info.last_name,
        email: auth.info.email,
        picture: auth.info.image
      }
      user.save!
    end
  end

  def self.teams_list(user)
    user.user_teams.collect(&:team_id)
  end

  # Returns User team ids
  def teams_ids
    user_teams.collect(&:team_id)
  end

  # Returns User team names
  def teams_names
    user_teams.map { |user_team| user_team.team[:team_name] }
  end

  # Returns team names for which user is admin
  def teams_acting_as_admin
    team_admins.map { |team_admin| team_admin.team[:team_name] }
  end

  # Checks whether User has teams or not
  def no_teams?
    user_teams.empty?
  end

  # User full name
  def name
    first_name + ' ' + last_name
  end
end

app/controllers/user_controller.rb
# frozen_string_literal: true

# This class contains User related functions
class UserController < ApplicationController
  before_action :authenticate
  before_action :check_user_has_teams
  before_action :check_same_user

  def show
  end

  private
  def check_same_user
    if params[:id].to_i != current_user.id
      flash[:danger] = "You dont have privileges to perform this action"
      redirect_to questions_path
    end
  end
end

app/views/user/show.html.erb
<div class="container emp-profile">
            <form method="post">
                <div class="row">
                    <div class="col-md-4">
                        <div class="profile-img">
                           <%= image_tag current_user.picture %>
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="profile-head">
                                    <h5>
                                        <%= current_user.name %>
                                    </h5>
                                    <p class="proile-rating">Member of : <span>
                                       <% current_user.teams_names.each do |team_name| %>
                                        <%= team_name+", " %>
                                       <% end %>
                                    </span></p>

                                    <p class="proile-rating">Admin of : <span>
                                       <% current_user.teams_acting_as_admin.each do |team_name| %>
                                        <%= team_name+", " %>
                                       <% end %>
                                    </span></p>
                            <ul class="nav nav-tabs" id="myTab" role="tablist">
                                <li class="nav-item">
                                    <a class="nav-link active" id="home-tab" data-toggle="tab" href="#home" role="tab" aria-controls="home" aria-selected="true">About</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" id="questions-tab" data-toggle="tab" href="#questions" role="tab" aria-controls="questions" aria-selected="false">Questions</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" id="answers-tab" data-toggle="tab" href="#answers" role="tab" aria-controls="answers" aria-selected="false">Answers</a>
                                </li>
                            </ul>
                        </div>
                    </div>
                    <div class="col-md-2">
                        <%= link_to 'Update Teams',edit_user_team_path(current_user),class: 'btn btn-primary' %>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-4">
                        <div class="profile-work">
                            <br>
                            <button type="button" class="btn btn-primary">
                             Questions <span class="badge badge-light"><%= current_user.questions.where.not(status_code_id: 4).count %></span>
                            </button><br>
                            <button type="button" class="btn btn-success">
                             Answers <span class="badge badge-light"><%= current_user.answers.count %></span>
                            </button><br>

                        </div>
                    </div>
                    <div class="col-md-8">
                        <div class="tab-content profile-tab" id="myTabContent">
                            <div class="tab-pane fade show active" id="home" role="tabpanel" aria-labelledby="home-tab">
                                        <div class="row">
                                            <div class="col-md-6">
                                                <label>Name</label>
                                            </div>
                                            <div class="col-md-6">
                                                <p><%= current_user.first_name+" "+current_user.last_name %></p>
                                            </div>
                                        </div>
                                        <div class="row">
                                            <div class="col-md-6">
                                                <label>Email</label>
                                            </div>
                                            <div class="col-md-6">
                                                <p><%= current_user.email %></p>
                                            </div>
                                        </div>
                                        <div class="row">
                                            <div class="col-md-6">
                                                <label>Account Created</label>
                                            </div>
                                            <div class="col-md-6">
                                                <p><%= current_user.created_at %></p>
                                            </div>
                                        </div>
                            </div>

                            <div class="tab-pane fade" id="questions" role="tabpanel" aria-labelledby="questions-tab">
                                <div class="row">
                                    <div class="col-md-12">

                                        <%= render 'questions/questiondisplay', obj: Question.get_displayable(current_user) %>
                                    </div>
                                </div>
                            </div>

                            <div class="tab-pane fade" id="answers" role="tabpanel" aria-labelledby="answers-tab">
                                <div class="row">
                                    <div class="col-md-12">
                                        <% current_user.answers.each do |answer| %>
        <div class="media text-muted pt-3">
          <div class="media-body pb-3 mb-0 small lh-125 border-bottom border-gray">
            <div class="d-flex justify-content-between align-items-center w-100">
              <span class="row">

                        <table>
                          <tr>
                            <td>
                         <span class="text-center">
                               <%= link_to like_question_answer_path(answer.question.id,answer),class:"like",method: :put do %>
                               <i class="fa fa-thumbs-up fa-2x" aria-hidden="true"></i>
                               <% end %>

                                <h3><%= answer.up_vote_count %></h3>
                              </span>
                              </td>
                              <td>
                              <span class="text-center" style="padding-left: 13px;">
                                 <%= link_to unlike_question_answer_path(answer.question.id,answer),class:"like",method: :put do %>
                               <i class="fa fa-thumbs-down fa-2x" aria-hidden="true"></i>
                               <% end %>
                                <h3><%= answer.down_vote_count %></h3>
                              </span>
                              </td></tr></table>
            </span>
            <span>
             <%= link_to answer.description, question_answer_path(answer.question,answer), class:'text-gray-dark' %>
              </span>
              <span>

              <% if current_user == answer.user %>
              <%= link_to 'Edit', edit_question_answer_path(answer.question, answer), class: 'btn btn-info' %>
              <%= link_to 'destroy', question_answer_path(answer.question, answer),method: :delete, data:{confirm:'Are you sure?'}, class: 'btn btn-danger' %>
            <% end %>
            </span>

            </div>
          </div>
        </div>
        <% end %>
                                    </div>
                                </div>
                            </div>

                        </div>
                    </div>
                </div>
            </form>
        </div>