config/routes.rb
Rails.application.routes.draw do

  get 'tags/new'
  get 'search', to: 'search#new', as: 'search'
  get 'login', to: redirect('/auth/google_oauth2'), as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'
  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')
  get 'user/:id', to: 'user#show', as: 'user'
  root to: "sessions#new"

  resources :questions do
    member do
        put "like" => "questions#upvote"
        put "unlike" => "questions#downvote"
				put "close" => "questions#close"
      end
		  resources :answers do
        member do
          put "like" => "answers#upvote"
          put "unlike" => "answers#downvote"
  				put "accept" => "answers#accept"
        end
      end
  end
  resources :user_teams
  resources :teams

end

app/views/layouts/_messages.html.erb
<div class="row">
	<div class="col-md-12">
	<% flash.each do |name,msg| %>
	<div class='alert alert-<%="#{name}" %>'>
		<a href="#" class="close" data-dismiss="alert">&#215;</a>
		<%= content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String) %>
	</div>
    <% end %>
	</div>
</div>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
 <%= link_to "Team Stackoverflow", root_path, class: "navbar-brand"%>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">

    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
      <li class="nav-item">
        <%= link_to "Home",root_path, class: 'nav-link' %>
      </li>

      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Questions
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <%= link_to "View Questions",questions_path, class: 'dropdown-item' %>
          <%= link_to "Ask Question",new_question_path, class: 'dropdown-item' %>
        </div>
      </li>
      <% end %>
    </ul>

      <%= form_for(:search, url:search_path, method: :get, :html => {class:"form-inline my-2 my-lg-0"}) do |f|   %>
      <%= f.text_field :key,class:'form-control mr-sm-2 md-12',placeholder: 'Search', value: (@key if @key.present?) %>
      <%= f.submit "Search", class: "btn btn-outline-success my-2 my-sm-0" %>
    <% end %>

    <ul class="navbar-nav">
      <% if user_signed_in? %>
      <li class="nav-item">
        <%= link_to "Profile",user_path(current_user), class: 'nav-link' %>
      </li>

      <li class="nav-item">
        <%= link_to "Logout",logout_path, class: 'nav-link' %>
      </li>
      <% end %>
    </ul>

  </div>

</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TeamStackoverflow</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
  </head>

  <body>
    <main role="main">
   <%= render 'layouts/navigation' %>
   <div class="container"> <%= render 'layouts/messages' %></div>
    <%= yield %>
  </main>

  </body>
</html>